# setting all project filters
# ---- PROJECT FILTER  --- BEGIN
# ---- GUI FILTER  --- BEGIN
set(PROJECT_GUI_SRC_DIR ${PROJECT_SRC_DIR}gui/)
set(PROJECT_GUI_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}gui/)
set(GUI_FILTER ${GUI_FILTER}
    ${PROJECT_GUI_SRC_DIR}GUI.cpp
    ${PROJECT_GUI_INCLUDE_DIR}GUI.hpp
)
# ---- GUI FILTER  --- END

# ---- RENDERER FILTER  --- BEGIN
set(PROJECT_RENDERER_SRC_DIR ${PROJECT_SRC_DIR}renderer/)
set(PROJECT_RENDERER_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}renderer/)
set(RENDERER_FILTER ${RENDERER_FILTER}
    ${PROJECT_RENDERER_SRC_DIR}VulkanRenderer.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}VulkanRenderer.hpp
    ${PROJECT_RENDERER_SRC_DIR}PathTracing.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}PathTracing.hpp
    ${PROJECT_RENDERER_SRC_DIR}Raytracing.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}Raytracing.hpp
    ${PROJECT_RENDERER_SRC_DIR}Rasterizer.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}Rasterizer.hpp
    ${PROJECT_RENDERER_SRC_DIR}PostStage.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}PostStage.hpp
    ${PROJECT_RENDERER_SRC_DIR}CommandBufferManager.cpp
    ${PROJECT_RENDERER_INCLUDE_DIR}CommandBufferManager.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}GlobalUBO.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}GUIRendererSharedVars.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}QueueFamilyIndices.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}SceneUBO.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}SwapChainDetails.hpp
    ${PROJECT_RENDERER_INCLUDE_DIR}VulkanRendererConfig.hpp
)
# ---- RENDERER FILTER  --- END

# ---- PC FILTER  --- BEGIN
set(PROJECT_PC_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}renderer/pushConstants/)
set(PC_FILTER ${PC_FILTER}
    ${PROJECT_PC_INCLUDE_DIR}PushConstantPathTracing.hpp
    ${PROJECT_PC_INCLUDE_DIR}PushConstantPost.hpp
    ${PROJECT_PC_INCLUDE_DIR}PushConstantRasterizer.hpp
    ${PROJECT_PC_INCLUDE_DIR}PushConstantRayTracing.hpp
)
# ---- PC FILTER  --- END

# ---- AS FILTER  --- BEGIN
set(PROJECT_AS_SRC_DIR ${PROJECT_SRC_DIR}renderer/accelerationStructures/)
set(PROJECT_AS_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}renderer/accelerationStructures/)
set(AS_FILTER ${AS_FILTER}
    ${PROJECT_AS_INCLUDE_DIR}ASManager.hpp
    ${PROJECT_AS_INCLUDE_DIR}BottomLevelAccelerationStructure.hpp
    ${PROJECT_AS_INCLUDE_DIR}TopLevelAccelerationStructure.hpp
    ${PROJECT_AS_SRC_DIR}ASManager.cpp
)
# ---- AS FILTER  --- END

# ---- VULKAN_BASE FILTER  --- BEGIN
set(PROJECT_VULKAN_BASE_SRC_DIR ${PROJECT_SRC_DIR}vulkan_base/)
set(PROJECT_VULKAN_BASE_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}vulkan_base/)
set(VULKAN_BASE_FILTER ${VULKAN_BASE_FILTER}
    ${PROJECT_VULKAN_BASE_SRC_DIR}ShaderHelper.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanBuffer.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanBufferManager.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanDebug.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanDevice.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanImage.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanImageView.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanInstance.cpp
    ${PROJECT_VULKAN_BASE_SRC_DIR}VulkanSwapChain.cpp

    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}ShaderHelper.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanBuffer.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanBufferManager.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanDebug.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanDevice.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanImage.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanImageView.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanInstance.hpp
    ${PROJECT_VULKAN_BASE_INCLUDE_DIR}VulkanSwapChain.hpp
)
# ---- VULKAN_BASE FILTER  --- END

# ---- SCENE FILTER  --- BEGIN
set(PROJECT_SCENE_SRC_DIR ${PROJECT_SRC_DIR}scene/)
set(PROJECT_SCENE_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}scene/)
set(SCENE_FILTER ${SCENE_FILTER}
    ${PROJECT_SCENE_SRC_DIR}ObjLoader.cpp
    ${PROJECT_SCENE_SRC_DIR}Model.cpp
    ${PROJECT_SCENE_SRC_DIR}Mesh.cpp
    ${PROJECT_SCENE_SRC_DIR}Scene.cpp
    ${PROJECT_SCENE_SRC_DIR}Camera.cpp
    ${PROJECT_SCENE_SRC_DIR}SceneConfig.cpp
    ${PROJECT_SCENE_SRC_DIR}Texture.cpp
    ${PROJECT_SCENE_SRC_DIR}Vertex.cpp
    
    ${PROJECT_SCENE_INCLUDE_DIR}ObjMaterial.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Model.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}ObjLoader.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Mesh.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Vertex.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Scene.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}SceneConfig.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}GUISceneSharedVars.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}ObjectDescription.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Texture.hpp
    ${PROJECT_SCENE_INCLUDE_DIR}Camera.hpp

)
# ---- SCENE FILTER  --- END

# ---- WINDOW FILTER  --- BEGIN
set(PROJECT_WINDOW_SRC_DIR ${PROJECT_SRC_DIR}window/)
set(PROJECT_WINDOW_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}window/)
set(WINDOW_FILTER ${WINDOW_FILTER}
    ${PROJECT_WINDOW_SRC_DIR}Window.cpp
    ${PROJECT_WINDOW_INCLUDE_DIR}Window.hpp
)
# ---- WINDOW FILTER  --- END

# ---- UTIL FILTER  --- BEGIN
set(PROJECT_UTIL_SRC_DIR ${PROJECT_SRC_DIR}util/)
set(PROJECT_UTIL_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}util/)
set(UTIL_FILTER ${UTIL_FILTER}
    ${PROJECT_UTIL_SRC_DIR}File.cpp
    ${PROJECT_UTIL_INCLUDE_DIR}File.hpp
)
# ---- UTIL FILTER  --- END

# ---- APP FILTER  --- BEGIN
set(PROJECT_APP_SRC_DIR ${PROJECT_SRC_DIR}app/)
set(PROJECT_APP_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}app/)
set(APP_FILTER ${APP_FILTER}
    ${PROJECT_APP_SRC_DIR}App.cpp
    ${PROJECT_APP_INCLUDE_DIR}App.hpp
)
# ---- APP FILTER  --- END

# ---- COMMON FILTER  --- BEGIN
set(PROJECT_COMMON_SRC_DIR ${PROJECT_SRC_DIR}common/)
set(PROJECT_COMMON_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}common/)
set(COMMON_FILTER ${COMMON_FILTER}
    ${PROJECT_COMMON_INCLUDE_DIR}FormatHelper.hpp
    ${PROJECT_COMMON_INCLUDE_DIR}Globals.hpp
    ${PROJECT_COMMON_INCLUDE_DIR}MemoryHelper.hpp
    ${PROJECT_COMMON_INCLUDE_DIR}Utilities.hpp
)
# ---- COMMON FILTER  --- END

# ---- MEMORY FILTER  --- BEGIN
set(PROJECT_MEMORY_SRC_DIR ${PROJECT_SRC_DIR}memory/)
set(PROJECT_MEMORY_INCLUDE_DIR ${PROJECT_INCLUDE_DIR}memory/)
set(MEMORY_FILTER ${MEMORY_FILTER}
    ${PROJECT_MEMORY_INCLUDE_DIR}Allocator.hpp
    ${PROJECT_MEMORY_SRC_DIR}Allocator.cpp
)
# ---- MEMORY FILTER  --- END

# ---- MAIN FILTER  --- BEGIN
set(PROJECT_MAIN_SRC_DIR ${PROJECT_SRC_DIR})
set(MAIN_FILTER ${MAIN_FILTER}
    ${PROJECT_MAIN_SRC_DIR}Main.cpp
)
# ---- MAIN FILTER  --- END