.TH "C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/App.cpp" 3 "Tue Jun 7 2022" "Version 1.9" "GraphicsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/App.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'App\&.h'\fP
.br
\fC#include <vulkan/vulkan\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <glm/glm\&.hpp>\fP
.br
\fC#include <glm/mat4x4\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'GUI\&.h'\fP
.br
\fC#include 'VulkanRenderer\&.hpp'\fP
.br
\fC#include 'Window\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLFW_INCLUDE_NONE\fP"
.br
.ti -1c
.RI "#define \fBGLFW_INCLUDE_VULKAN\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_RADIANS\fP"
.br
.ti -1c
.RI "#define \fBGLM_FORCE_DEPTH_ZERO_TO_ONE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GLFW_INCLUDE_NONE"

.PP
Definition at line \fB4\fP of file \fBApp\&.cpp\fP\&.
.SS "#define GLFW_INCLUDE_VULKAN"

.PP
Definition at line \fB5\fP of file \fBApp\&.cpp\fP\&.
.SS "#define GLM_FORCE_DEPTH_ZERO_TO_ONE"

.PP
Definition at line \fB9\fP of file \fBApp\&.cpp\fP\&.
.SS "#define GLM_FORCE_RADIANS"

.PP
Definition at line \fB8\fP of file \fBApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GraphicsEngine from the source code\&.
