.TH "C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/util/File.cpp" 3 "Tue Jun 7 2022" "Version 1.9" "GraphicsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/util/File.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'File\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for GraphicsEngine from the source code\&.
