.TH "C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/scene/ObjLoader.cpp" 3 "Tue Jun 7 2022" "Version 1.9" "GraphicsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/scene/ObjLoader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ObjLoader\&.h'\fP
.br
\fC#include <tiny_obj_loader\&.h>\fP
.br
\fC#include 'File\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTINYOBJLOADER_IMPLEMENTATION\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TINYOBJLOADER_IMPLEMENTATION"

.PP
Definition at line \fB2\fP of file \fBObjLoader\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GraphicsEngine from the source code\&.
