.TH "C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/window/Window.cpp" 3 "Tue Jun 7 2022" "Version 1.9" "GraphicsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/window/Window.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Window\&.h'\fP
.br
\fC#include <imgui\&.h>\fP
.br
\fC#include <imgui_impl_glfw\&.h>\fP
.br
\fC#include <imgui_impl_vulkan\&.h>\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBonErrorCallback\fP (int error, const char *description)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void onErrorCallback (int error, const char * description)\fC [static]\fP"

.PP
Definition at line \fB10\fP of file \fBWindow\&.cpp\fP\&.
.PP
.nf
10                                                                 {
11   fprintf(stderr, "GLFW Error %d: %s\n", error, description);
12 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for GraphicsEngine from the source code\&.
