#define UBO_VIEW_PROJECTION_BINDING 0
#define UBO_DIRECTIONS_BINDING 1

// ---- RAYTRACING BINDING ---- START
#define TLAS_BINDING 0
#define OUT_IMAGE_BINDING 1
#define OBJECT_DESCRIPTION_BINDING 3
#define TEXTURES_BINDING 4
// ---- RAYTRACING BINDING ---- END


