#pragma once
// ----- RASTERIZER ----- START
#define UBO_VIEW_PROJECTION_BINDING 0
#define UBO_DIRECTIONS_BINDING 1
#define SAMPLER_BINDING 0

// ----- RASTERIZER ----- END
// 
// ---- RAYTRACING BINDING ---- START
// --- TLAS
#define TLAS_BINDING 0
// --- TLAS
// --- OUT IMAGE
#define OUT_IMAGE_BINDING 1
// --- OUT IMAGE
// --- OBJECT DESCR
#define OBJECT_DESCRIPTION_BINDING 2
// --- OBJECT DESCR
// --- TEXTURES
#define TEXTURES_BINDING 3
#define SAMPLER_BINDING_RT 4
// --- TEXTURES
// ---- RAYTRACING BINDING ---- END
