
// ----- RASTERIZER ----- START
#define UBO_VIEW_PROJECTION_SET 0
#define UBO_VIEW_PROJECTION_BINDING 0

#define UBO_DIRECTIONS_SET 0
#define UBO_DIRECTIONS_BINDING 1

#define SAMPLER_SET 1
#define SAMPLER_BINDING 0

// ----- RASTERIZER ----- END
// 
// ---- RAYTRACING BINDING ---- START
// --- TLAS
#define TLAS_BINDING 0
#define TLAS_SET 1
// --- TLAS
// --- OUT IMAGE
#define OUT_IMAGE_BINDING 1
#define OUT_IMAGE_SET 1
// --- OUT IMAGE
// --- OBJECT DESCR
#define OBJECT_DESCRIPTION_BINDING 2
#define OBJECT_DESCRIPTION_SET 1
// --- OBJECT DESCR
// --- TEXTURES
#define TEXTURES_BINDING 3
#define SAMPLER_BINDING_RT 4
#define TEXTURES_SET 1
// --- TEXTURES
// ---- RAYTRACING BINDING ---- END


