// ----- RASTERIZER ----- START
#define globalUBO_BINDING 0
#define sceneUBO_BINDING 1
#define OBJECT_DESCRIPTION_BINDING 3
#define SAMPLER_BINDING 0
// ----- RASTERIZER ----- END

// ---- RAYTRACING BINDING ---- START
#define TLAS_BINDING 0
#define OUT_IMAGE_BINDING 1
#define TEXTURES_BINDING 2
#define SAMPLER_BINDING_RT 3
// --- TEXTURES
// ---- RAYTRACING BINDING ---- END


