#pragma once
#define UBO_VIEW_PROJECTION_BINDING 0
#define UBO_DIRECTIONS_BINDING 1

// ---- RAYTRACING BINDING ---- START
#define TLAS_BINDING 0
#define OUT_IMAGE 1
#define OBJ_DESCRIPTION 2
#define TEXTURES 3
// ---- RAYTRACING BINDING ---- END
