function(myproject_enable_coverage project_name)
  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    message(" -- ** Enabling coverage reporting**")
    target_compile_options(${project_name} INTERFACE --coverage -O0 -g)
    target_link_libraries(${project_name} INTERFACE --coverage)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    message(" -- ** Enabling coverage reporting**")
    target_compile_options(${project_name} INTERFACE -fprofile-instr-generate -fcoverage-mapping)
    target_link_libraries(${project_name} INTERFACE -fprofile-instr-generate -fcoverage-mapping)
  endif()
endfunction()
