.TH "C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/Main.cpp" 3 "Tue Jun 7 2022" "Version 1.9" "GraphicsEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/jonas/Desktop/GraphicsEngineVulkan/Src/Main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'App\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line \fB3\fP of file \fBMain\&.cpp\fP\&.
.PP
.nf
3            {
4   App application;
5   return application\&.run();
6 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for GraphicsEngine from the source code\&.
