GraphicsEngine: debug Namespace Reference
debug Namespace Reference
Functions
VKAPI_ATTR VkBool32 VKAPI_CALL debugUtilsMessengerCallback (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageType, const VkDebugUtilsMessengerCallbackDataEXT *pCallbackData, void *pUserData)
void setupDebugging (VkInstance instance, VkDebugReportFlagsEXT flags, VkDebugReportCallbackEXT callBack)
void freeDebugCallback (VkInstance instance)
VKAPI_ATTR VkBool32 VKAPI_CALL messageCallback (VkDebugReportFlagsEXT flags, VkDebugReportObjectTypeEXT objType, uint64_t srcObject, size_t location, int32_t msgCode, const char *pLayerPrefix, const char *pMsg, void *pUserData)
Variables
PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT
PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT
VkDebugUtilsMessengerEXT debugUtilsMessenger
int validationLayerCount
const char * validationLayerNames []
Function Documentation
debugUtilsMessengerCallback()
VKAPI_ATTR VkBool32 VKAPI_CALL debug::debugUtilsMessengerCallback (VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity, VkDebugUtilsMessageTypeFlagsEXT messageType, const VkDebugUtilsMessengerCallbackDataEXT * pCallbackData, void * pUserData)
Definition at line 10 of file VulkanDebug.cpp.
                      {
   // Select prefix depending on flags passed to the callback
   std::string prefix("");
   if (messageSeverity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT) {
     prefix = "VERBOSE: ";
   } else if (messageSeverity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT) {
     prefix = "INFO: ";
   } else if (messageSeverity &
              VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT) {
     prefix = "WARNING: ";
   } else if (messageSeverity & VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT) {
     prefix = "ERROR: ";
   }
   // Display message to default output (console/logcat)
   std::stringstream debugMessage;
   debugMessage << prefix << "[" << pCallbackData->messageIdNumber << "]["
                << pCallbackData->pMessageIdName
                << "] : " << pCallbackData->pMessage;
 #if defined(__ANDROID__)
   if (messageSeverity >= VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT) {
     LOGE("%s", debugMessage.str().c_str());
   } else {
     LOGD("%s", debugMessage.str().c_str());
   }
 #else
   if (messageSeverity >= VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT) {
     std::cerr << debugMessage.str() << "\n";
   } else {
     std::cout << debugMessage.str() << "\n";
   }
   fflush(stdout);
 #endif
   // The return value of this callback controls whether the Vulkan call that
   // caused the validation message will be aborted or not We return VK_FALSE as
   // we DON'T want Vulkan calls that cause a validation message to abort If you
   // instead want to have calls abort, pass in VK_TRUE and the function will
   // return VK_ERROR_VALIDATION_FAILED_EXT
   return VK_FALSE;
 }
Referenced by setupDebugging().
freeDebugCallback()
void debug::freeDebugCallback (VkInstance instance)
Definition at line 82 of file VulkanDebug.cpp.
{
   if (debugUtilsMessenger != VK_NULL_HANDLE) {
     vkDestroyDebugUtilsMessengerEXT(instance, debugUtilsMessenger, nullptr);
   }
 }
References debugUtilsMessenger, and vkDestroyDebugUtilsMessengerEXT.
Referenced by VulkanRenderer::cleanUp().
messageCallback()
VKAPI_ATTR VkBool32 VKAPI_CALL debug::messageCallback (VkDebugReportFlagsEXT flags, VkDebugReportObjectTypeEXT objType, uint64_t srcObject, size_t location, int32_t msgCode, const char * pLayerPrefix, const char * pMsg, void * pUserData)
setupDebugging()
void debug::setupDebugging (VkInstance instance, VkDebugReportFlagsEXT flags, VkDebugReportCallbackEXT callBack)
Definition at line 58 of file VulkanDebug.cpp.
{
   vkCreateDebugUtilsMessengerEXT =
       reinterpret_cast<PFN_vkCreateDebugUtilsMessengerEXT>(
           vkGetInstanceProcAddr(instance, "vkCreateDebugUtilsMessengerEXT"));
   vkDestroyDebugUtilsMessengerEXT =
       reinterpret_cast<PFN_vkDestroyDebugUtilsMessengerEXT>(
           vkGetInstanceProcAddr(instance, "vkDestroyDebugUtilsMessengerEXT"));
   VkDebugUtilsMessengerCreateInfoEXT debugUtilsMessengerCI{};
   debugUtilsMessengerCI.sType =
       VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT;
   debugUtilsMessengerCI.messageSeverity =
       VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
       VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT;
   debugUtilsMessengerCI.messageType =
       VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
       VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT;
   debugUtilsMessengerCI.pfnUserCallback = debugUtilsMessengerCallback;
   ASSERT_VULKAN(vkCreateDebugUtilsMessengerEXT(instance, &debugUtilsMessengerCI,
                                                nullptr, &debugUtilsMessenger),
                 "Failed to create debug messenger")
 }
References debugUtilsMessenger, debugUtilsMessengerCallback(), vkCreateDebugUtilsMessengerEXT, and vkDestroyDebugUtilsMessengerEXT.
Referenced by VulkanRenderer::VulkanRenderer().
Variable Documentation
debugUtilsMessenger
VkDebugUtilsMessengerEXT debug::debugUtilsMessenger
Definition at line 8 of file VulkanDebug.cpp.
Referenced by freeDebugCallback(), and setupDebugging().
validationLayerCount
int debug::validationLayerCount extern
validationLayerNames
const char* debug::validationLayerNames[] extern
vkCreateDebugUtilsMessengerEXT
PFN_vkCreateDebugUtilsMessengerEXT debug::vkCreateDebugUtilsMessengerEXT
Definition at line 6 of file VulkanDebug.cpp.
Referenced by setupDebugging().
vkDestroyDebugUtilsMessengerEXT
PFN_vkDestroyDebugUtilsMessengerEXT debug::vkDestroyDebugUtilsMessengerEXT
Definition at line 7 of file VulkanDebug.cpp.
Referenced by freeDebugCallback(), and setupDebugging().